name: My first workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: welcome message
          run: echo "My firt githu action"
        - name: list of files
          run: ls
        - name: read file
          run: cat README.md