name: Generate-cowsay
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: welcome message
          run: echo "My firt githu action"
        - name: Checkout
          uses: actions/checkout@main
        - name: Run script
          run: sh -x script.sh